import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/theme';

export default StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    width: '100%',
    height: '100%',
  },
  rootInner: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.primary,
    fontFamily: 'Space Grotesk',
    marginBottom: 8,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 15,
    color: COLORS.cardForeground,
    fontFamily: 'Inter',
    marginBottom: 24,
    textAlign: 'center',
  },
  button: {
    width: '100%',
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonText: {
    color: COLORS.primaryForeground,
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Space Grotesk',
    letterSpacing: 0.5,
  },
  skipButton: {
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  skipText: {
    color: COLORS.mutedForeground,
    fontSize: 14,
    fontFamily: 'Inter',
    letterSpacing: 0.3,
  },
  switchText: {
    color: COLORS.accent,
    fontSize: 15,
    fontFamily: 'Inter',
    marginTop: 8,
    textAlign: 'center',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
    width: '100%',
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.border,
  },
  orText: {
    marginHorizontal: 8,
    color: COLORS.mutedForeground,
    fontSize: 13,
    fontFamily: 'Inter',
  },
  socialButton: {
    width: '100%',
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 8,
    justifyContent: 'center',
  },
  socialIcon: {
    width: 32,
    height: 32,
  },
  bricksContainer: {
    width: '95%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bricksWithLogos: {
    flexDirection: 'row',
    width: '50%',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brick: {
    width: '100%',
    backgroundColor: COLORS.card,
    borderRadius: 14,
    marginBottom: 14,
    padding: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
});

